### ISSUE TITLE
UserWarning

### ISSUE THREAD

**Issue by goodnight111111111** [goutamyg/MVT#4]
./lib/train/data/loader.py:87: UserWarning: An output with one or more elements was resized since it had shape [1572864], which does not match the required output shape [1, 96, 128, 128]. This behavior is deprecated, and in a future PyTorch release outputs will not be resized unless they have zero elements. You can explicitly reuse an out tensor t by resizing it, inplace, to zero elements with t.resize_(0). (Triggered internally at  /opt/conda/conda-bld/pytorch_1656352464346/work/aten/src/ATen/native/Resize.cpp:17.)
  return torch.stack(batch, 1, out=out)

**Comment by goutamyg** [comment]
Hi, 

Thank you for your interest in our work. Regarding the warning you encountered, it seems to be related to an older version of PyTorch, which has been addressed in the [latest release](https://github.com/pytorch/pytorch/issues/71063). Since I conduct model training on a remote server, I haven't attempted to resolve or suppress this warning (although I acknowledge that it is annoying).

**Comment by goodnight111111111** [comment]
Thanks for your help, I got an error at epoch 10 when reproducing your code: RuntimeError:Given group=1, weight of size [16,3,3,3],expected input[1,64,32,32] to have 3 channels ,but got 64 channels instead.

**Comment by goutamyg** [comment]
Sorry for the delayed reply. Comment [these lines](https://github.com/goutamyg/MVT/blob/main/lib/test/tracker/mobilevit_track.py#L68-L78) and replace with ```self.z_dict1 = template.tensors```. I hope this fixes the error.

**Comment by goodnight111111111** [comment]
Thank you for your reply, but the problem is still not solved

**Comment by goutamyg** [comment]
With the above modification, the training code has no issues at my end, esp. after the 10th epoch. I hope you have modified the [mobilevit_track.py](https://github.com/goutamyg/MVT/blob/main/lib/test/tracker/mobilevit_track.py) file as follows: 

![Screenshot from 2024-04-24 11-49-40](https://github.com/goutamyg/MVT/assets/15650213/6b92d032-c337-4792-979b-0e9cffd36829)

Can you please share more info regarding the error message?

**Comment by goodnight111111111** [comment]
./lib/train/data/loader.py:87: UserWarning: An output with one or more elements was resized since it had shape [7340032], which does not match the required output shape [1, 112, 256, 256]. This behavior is deprecated, and in a future PyTorch release outputs will not be resized unless they have zero elements. You can explicitly reuse an out tensor t by resizing it, inplace, to zero elements with t.resize_(0). (Triggered internally at  /opt/conda/conda-bld/pytorch_1656352464346/work/aten/src/ATen/native/Resize.cpp:17.)
  return torch.stack(batch, 1, out=out)
./lib/models/mobilevit_track/layers/head.py:144: UserWarning: __floordiv__ is deprecated, and its behavior will change in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values. To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor').
  idx_y = idx // self.feat_sz

**Comment by goutamyg** [comment]
It looks like a warning message and should not halt the model training code. Please confirm.

**Comment by goodnight111111111** [comment]
Thanks for your help, which script should I run when I need.zip file when evaluating got10k

**Comment by goutamyg** [comment]
[This script](https://github.com/goutamyg/MVT/blob/main/tracking/convert_results_to_GOT10K_server_eval_format.py) will re-organize the GOT10k results into a folder suitable for their server evaluation (make sure you change the paths appropriately). Then you need to zip the resulting folder and submit it to the GOT10k eval server.
